### ISSUE TITLE
跨apk进程调用provider，没有响应

### ISSUE THREAD

**Issue by zemoLee** [Dovar66/DRouter#2]
按楼主作者的文档，集成完后。 整体编译打包apk时，跳转和调用provider都是正常。
配置MultiProgress后，使用multiRouter进行调用方法时，没有任何反馈。看日志也没错。
跟踪断点response返回广域路由正在启动中后，就没了。
进程名的配置，我按包名+debug 包配置的，应该没错，试了多种配置。还是无法响应。
不知道哪还有问题。

**Comment by Dovar66** [comment]
多进程除了实现IMultiProcess接口，还需要配置启用RouterPlugin插件，在文档里有写到

**Comment by zemoLee** [comment]
> 多进程除了实现IMultiProcess接口，还需要配置启用RouterPlugin插件，在文档里有写到

不行，宿主app的gradle中，我配置了RouterPlugin插件， 需要跨进程路由的module apk的gradle中也配置了插件RouterPlugin， 都是放在application之后。 还是没有任何反馈

**Comment by Dovar66** [comment]
你是用来跨APK吗？DRouter目前还不支持跨APK调用，不过有考虑接下来要引入这个功能。可以加我QQ847736308一起讨论
