### ISSUE TITLE
 编译失败: Execution failed for task ':router-api:compileDebugAidl'.

### ISSUE THREAD

**Issue by huangbqsky** [Dovar66/DRouter#4]
报错提示:
Execution failed for task ':router-api:compileDebugAidl'.
> java.lang.IllegalStateException: aidl is missing from '/Users/xxxx/android/sdk/build-tools/28.0.3/aidl'

**Comment by Dovar66** [comment]
> 报错提示:
> Execution failed for task ':router-api:compileDebugAidl'.
> 
> > java.lang.IllegalStateException: aidl is missing from '/Users/xxxx/android/sdk/build-tools/28.0.3/aidl'

这个报错是指向你的编译工具缺了文件，把28.0.3这个目录删了重新下载就好了

**Comment by huangbqsky** [comment]
确实是把28.0.3这个目录删了重新下载就好了，多谢！

**Comment by huangbqsky** [comment]
> > 报错提示:
> > Execution failed for task ':router-api:compileDebugAidl'.
> > > java.lang.IllegalStateException: aidl is missing from '/Users/xxxx/android/sdk/build-tools/28.0.3/aidl'
> 
> 这个报错是指向你的编译工具缺了文件，把28.0.3这个目录删了重新下载就好了

顺楼再问下，建议增加粘性消息的支持，其实粘性消息蛮多使用场景的，尤其是多进程的粘性消息
